### ISSUE TITLE
Ensure that it is clear whether Water Year or Contract Year is the aggregating period

### ISSUE THREAD

**Issue by nsosorio** [CentralValleyModeling/calsim-dash#11]
For SWP delivery calculations, we use the contract year (Jan-Dec). But for everything else like those we have in the Detail Tab, it looks like we have the option to choose WY or CY. I think this should be clear and could go at the top.

**Comment by dwr-zroy** [comment]
Updated the plots to specify what year type they use.
![image](https://github.com/user-attachments/assets/2c6c6700-c983-4891-9e4f-bdd71a1d8e27)
![image](https://github.com/user-attachments/assets/10098fb7-cea5-4adb-b12c-b5d0c20a6894)
![image](https://github.com/user-attachments/assets/f5a41fb0-636c-4ab2-9576-ae0e57c96e45)
![image](https://github.com/user-attachments/assets/414ace43-cf59-4a29-a7e8-73bd1d5c7667)

Update made on `sprint-zroy`, pull request will be opened following sprint.
