### ISSUE TITLE
Ensure that there are descriptions on each page for interpretability

### ISSUE THREAD

**Issue by nsosorio** [CentralValleyModeling/calsim-dash#15]
The home page has a good amount of descriptions which is important as the starting page. However, all of the other pages could use some more information on what to expect and do on the other tabs.

**Comment by dwr-zroy** [comment]
@nsosorio Check out the new tooling for loading static text from markdown files. The function is called `load_markdown` and you can see it being used on the home page. This could be useful for putting descriptions on pages without needing to hard-code the text.

**Comment by nsosorio** [comment]
> @nsosorio Check out the new tooling for loading static text from markdown files. The function is called `load_markdown` and you can see it being used on the home page. This could be useful for putting descriptions on pages without needing to hard-code the text.

I just saw this as I tried to merge my text boxes. I have some conflicts to deal with as I try to learn this new syntax.

**Comment by nsosorio** [comment]
9511c89 addresses this
