### ISSUE TITLE
Use consistent plot backgrounds

### ISSUE THREAD

**Issue by nsosorio** [CentralValleyModeling/calsim-dash#16]
Some plot backgrounds are white whereas some plots have a grey background.
See the Drilldown page.
![image](https://github.com/user-attachments/assets/dab16cd0-131f-433e-83a2-99c3b7da28f6)

The Home page seems just to use a white background. It might be better to apply that across the board for consistency's sake unless there are reasons beyond aesthetics.

**Comment by dwr-rhoang** [comment]
Closed with https://github.com/CentralValleyModeling/calsim-recon/commit/1974ef60bf7edc677fc3fa46876290594d1e98f7
