### ISSUE TITLE
Add annual timeseries view

### ISSUE THREAD

**Issue by nsosorio** [CentralValleyModeling/calsim-dash#2]
It could be an annual sum or an annual average depending on the variable.
Annual average of storage and annual sum for everything else?

In the DCR 2021 Tableau dashboard, we displayed annual sum timeseries for SWP deliveries and exports.
![image](https://github.com/user-attachments/assets/71bbbd67-b8a2-488d-a62a-f61d5dcf4d9e)

**Comment by dwr-zroy** [comment]
Added to the Drilldown page. Switches available for multiple aggregations and year types.
